export const ROUTES = {
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  changePassword: '/ubah-password',
  dashboard: '/dashboard',
  persetujuan: '/persetujuan',
  persetujuanDetail: '/persetujuan/:id',
  persetujuanWorkflow: '/persetujuan/alur',
  akademik: {
    kurikulum: '/akademik/kurikulum',
    kurikulumDetail: '/akademik/kurikulum/:id',
    mataKuliah: '/akademik/mata-kuliah',
    mataKuliahDetail: '/akademik/mata-kuliah/:id',
    kelasJadwal: '/akademik/kelas-jadwal',
    kelasJadwalDetail: '/akademik/kelas-jadwal/:id',
    programStudi: '/akademik/program-studi',
    programStudiDetail: '/akademik/program-studi/:id',
    krs: '/akademik/krs',
    absensi: '/akademik/absensi',
    penilaian: '/akademik/penilaian',
    ujian: '/akademik/ujian',
    ujianDetail: '/akademik/ujian/:id',
    ujianRekap: '/akademik/ujian/:id/rekap',
    bankSoal: '/akademik/bank-soal',
    // Dosen wali / Bagian Akademik menyetujui KRS mandiri mahasiswa.
    persetujuanKrs: '/akademik/persetujuan-krs',
    // Dosen pengampu: materi, tugas, penilaian tugas kelasnya sendiri.
    kelasSaya: '/akademik/kelas-saya',
    kelasSayaDetail: '/akademik/kelas-saya/:id',
    // Bagian Akademik meninjau pengajuan akademik mahasiswa.
    pengajuanMahasiswa: '/akademik/pengajuan-mahasiswa',
  },
  mahasiswa: '/mahasiswa',
  mahasiswaDetail: '/mahasiswa/:id',
  dosen: '/dosen',
  dosenDetail: '/dosen/:id',
  pegawai: '/pegawai',
  pegawaiDetail: '/pegawai/:id',
  keuangan: {
    tagihan: '/keuangan/tagihan',
    tagihanDetail: '/keuangan/tagihan/:id',
    pembayaran: '/keuangan/pembayaran',
    beasiswa: '/keuangan/beasiswa',
    beasiswaDetail: '/keuangan/beasiswa/:id',
  },
  skripsi: '/skripsi',
  skripsiDetail: '/skripsi/:id',
  magangMbkm: '/magang-mbkm',
  magangMbkmDetail: '/magang-mbkm/:id',
  perpustakaan: '/perpustakaan',
  perpustakaanDetail: '/perpustakaan/:id',
  alumni: '/alumni',
  alumniDetail: '/alumni/:id',
  pengumuman: '/pengumuman',
  pengumumanDetail: '/pengumuman/:id',
  laporan: '/laporan',
  pengaturan: {
    roles: '/pengaturan/roles',
    permissions: '/pengaturan/permissions',
    userRoles: '/pengaturan/user-roles',
    systemSettings: '/pengaturan/system-settings',
    featureFlags: '/pengaturan/feature-flags',
    notifications: '/pengaturan/notifikasi',
    auditLog: '/pengaturan/audit-log',
    security: '/pengaturan/keamanan',
  },
  platform: {
    universities: '/platform/universitas',
    security: '/platform/keamanan',
  },
  portal: {
    profil: '/portal/profil',
    akademik: '/portal/akademik',
    krs: '/portal/krs',
    jadwal: '/portal/jadwal-kuliah',
    khs: '/portal/khs',
    transkrip: '/portal/transkrip',
    nilai: '/portal/nilai',
    absensi: '/portal/absensi',
    dokumen: '/portal/dokumen',
    mataKuliah: '/portal/mata-kuliah',
    mataKuliahDetail: '/portal/mata-kuliah/:id',
    materi: '/portal/materi',
    tugas: '/portal/tugas',
    tugasDetail: '/portal/tugas/:id',
    ujian: '/portal/ujian',
    ujianKerjakan: '/portal/ujian/:id/kerjakan',
    ujianHasil: '/portal/ujian/hasil/:attemptId',
    kalender: '/portal/kalender',
    pengajuan: '/portal/pengajuan',
    pengumuman: '/portal/pengumuman',
    notifikasi: '/portal/notifikasi',
    pengaturan: '/portal/pengaturan',
  },
  // Akses ujian publik lewat link/QR + NIM, tanpa login — standalone,
  // sengaja di luar DashboardLayout/portal (lihat App.tsx & PublicExamLayout).
  examPublic: {
    access: '/exam/:accessToken',
    attempt: '/exam/:accessToken/attempt/:sessionToken',
    result: '/exam/:accessToken/result/:sessionToken',
  },
} as const
