export const ROUTES = {
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  dashboard: '/dashboard',
  persetujuan: '/persetujuan',
  persetujuanDetail: '/persetujuan/:id',
  persetujuanWorkflow: '/persetujuan/alur',
  akademik: {
    kurikulum: '/akademik/kurikulum',
    mataKuliah: '/akademik/mata-kuliah',
    kelasJadwal: '/akademik/kelas-jadwal',
    krs: '/akademik/krs',
    absensi: '/akademik/absensi',
    penilaian: '/akademik/penilaian',
  },
  mahasiswa: '/mahasiswa',
  dosen: '/dosen',
  pegawai: '/pegawai',
  keuangan: {
    tagihan: '/keuangan/tagihan',
    beasiswa: '/keuangan/beasiswa',
  },
  skripsi: '/skripsi',
  magangMbkm: '/magang-mbkm',
  perpustakaan: '/perpustakaan',
  alumni: '/alumni',
  pengumuman: '/pengumuman',
  laporan: '/laporan',
  pengaturan: {
    roles: '/pengaturan/roles',
    permissions: '/pengaturan/permissions',
    userRoles: '/pengaturan/user-roles',
    systemSettings: '/pengaturan/system-settings',
    featureFlags: '/pengaturan/feature-flags',
    notifications: '/pengaturan/notifikasi',
    auditLog: '/pengaturan/audit-log',
    security: '/pengaturan/keamanan',
  },
} as const
